Add: Social Login
wecode-bootcamp-korea/39-2nd-bugbug-backend pull request #4
Opened 2022-11-30 13:10 UTC by hosose

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 카카오톡 social login 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- axios 모듈을 이용하여 서버 내에서 카카오에서 받은 code와 토큰을 인증하여 카카오톡 id, email, nickname을 불러와 database에 저장

<br />

## :: 테스트 결과 이미지
- Login Success

![login_success](https://user-images.githubusercontent.com/112751572/204803057-3d7702d2-39ba-498e-8101-f108e3b56830.png)

- Users Database

![users_database](https://user-images.githubusercontent.com/112751572/204804485-5f6a273e-ae74-4b7d-b2d0-9d1cf802822e.png)

<br />

## :: 기타 질문 및 특이 사항

2022-12-01 03:33 UTC, bigfanoftim requested changes
Test Code도 작성 부탁드립니다!

2022-12-01 03:33 UTC, bigfanoftim commented on src/controllers/userController.js
> +  }
제 생각에는 카카오 엑세스 토큰을 가지고 카카오 API를 호출했을 때 그 응답이 성공적이라면 `kakao_id`가 안넘어오는 경우는 없다고 생각됩니다. 
추가로 올바르지 않은 응답에 대한 예외 처리는 userService의 `getKakaoUserInfo` 메소드에서 해줘야 할 것 같아요.

2022-12-01 03:33 UTC, bigfanoftim commented on src/services/userService.js
> +  console.log(typeof authorizationCode);
👀

2022-12-05 01:05 UTC, Jon9Beom reviewed
테스트 코드 작성하느라 너무 고생많으셨습니다 세호님👍 아래 코멘트 반영해주시면 merge하겠습니다!

2022-12-05 01:05 UTC, Jon9Beom commented on .env.test
> +DATABASE_URL="mysql://root:1q2w3e4r!@127.0.0.1:3306/BUGBUG_test"
.env.test 도 같이 올라왔네요🧐

2022-12-05 01:05 UTC, Jon9Beom commented on src/controllers/userController.js
> +  res.status(200).json(userInfo);
```suggestion
  return res.status(200).json(userInfo);
```
실제 return keyword가 빠져도 이후 로직이 없기 때문에 동작에는 문제가 없지만 method의 실행문 안에서 response를 보내준 이후로 더 처리할 코드가 없다면 return을 통해 확실히 마무리 해주시는 것이 좋습니다

2022-12-05 01:05 UTC, Jon9Beom commented on src/models/userDao.js
> +      *
SELECT문을 쓸 때에는 정말 column 전부가 필요하더라도, 모든 열을 나타내는 메타 문자인 애스터리스크(`*`)를 쓰기보다 직접적으로 `users.id, users.name, users.email, ...` 처럼 직접적으로 컬럼들을 나열하며 작성해주시는 것이 좋습니다. 이유는 직접 다른 사람의 코드를 수정 혹은 파악이 필요한 경우가 매우 흔한 실무에서는 `SELECT * FROM ...` 과 같이 작성되어 있으면 해당 query에서 불러오는 data가 무엇인지 알기 위해 table structure를 다시 한 번 확인해봐야 하는 작업이 추가되기 때문입니다-! :)

2022-12-05 01:05 UTC, Jon9Beom commented on src/services/userService.js
> +  }
```suggestion
  if (!user) raiseCustomError(`USER_DOES_NOT_EXIST`, 401);
```

2022-12-05 01:05 UTC, Jon9Beom commented on src/services/userService.js
> +  }
```suggestion
  if (user) await updateUserInfo(kakaoId, name, email);
```
가독성을 해치지 않는 선에서는 코드는 짧으면 짧을 수록 좋습니다🫡

2022-12-05 01:05 UTC, Jon9Beom commented on tests/users.test.js
> +    await axios.mockResolvedValue(userInfo);
data setup을 위한 users 같은 경우는 테스트 파일 상단에서 작성되어도 좋으나, `token`, `userInfo` 같은 것은 해당 테스트 함수 안에 직접 적으로 작성되는 것이 좋습니다! 이유는 테스트 코드가 case별로 상세하게 작성되다보면 token 혹은 userInfo를 다르게 활용 되는 경우가 당연히 있을 것 같고, 실제 테스트 코드를 작성하다보면 하나의 파일에 수백줄이 넘어가는 경우가 아주 흔합니다! 그렇게 될 경우 변수로서 들어간 객체를 찾기 위해 노력해야 하는 경우도 생길 수 있습니다 나중에 리팩토링 때 수정해주세요 :)

2022-12-05 02:13 UTC, hosose commented on .env.test
> +DATABASE_URL="mysql://root:1q2w3e4r!@127.0.0.1:3306/BUGBUG_test"
삭제하겠습니다.

2022-12-05 02:20 UTC, hosose commented on src/services/userService.js
> +  }
이렇게도 사용가능하군요!

2022-12-05 03:38 UTC, hosose commented on tests/users.test.js
> +    await axios.mockResolvedValue(userInfo);
네 알겠습니다. case 별로 다를 수 있기 때문에 변경해야하는 것 이해했습니다.

2022-12-05 04:25 UTC, Jon9Beom commented
LGTM 👍

2022-12-05 04:25 UTC, merged